import {AudioEngine} from './audio.js';
import {applyScaleAttraction,clampBpm} from './music.js';
import {pointerRole,normalizePressure} from './input.js';
import {appendPoint,eraseStrokeSegments,sampleStrokeIntersections} from './strokes.js';
import {DEFAULT_VIEWPORT,clampViewport,panViewport,screenToWorld,worldToScreen,zoomViewport} from './viewport.js';
const canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});
const controls={play:document.querySelector('#playButton'),bpm:document.querySelector('#bpmInput'),key:document.querySelector('#keySelect'),scale:document.querySelector('#scaleSelect'),tool:document.querySelector('#toolButton'),toolLabel:document.querySelector('#toolLabel'),clear:document.querySelector('#clearButton'),undo:document.querySelector('#undoButton'),redo:document.querySelector('#redoButton'),settings:document.querySelector('#settingsButton'),settingsPanel:document.querySelector('#settingsPanel'),closeSettings:document.querySelector('#closeSettingsButton'),wave:document.querySelector('#waveSelect'),brightness:document.querySelector('#brightnessInput'),ambience:document.querySelector('#ambienceInput'),attraction:document.querySelector('#attractionInput'),toast:document.querySelector('#toast')};
const state={strokes:loadStrokes(),draft:null,tool:'draw',viewport:{...DEFAULT_VIEWPORT},bpm:120,key:0,scale:'major',attraction:.78,waveform:'triangle',brightness:4200,ambience:.16,playing:false,past:[],future:[],eraseBaseline:null,eraseChanged:false,drawPointerId:null,eraserScreen:null,touches:new Map(),touchGesture:null};
const audio=new AudioEngine({sampleAtX:(x)=>sampleStrokeIntersections(state.strokes,x,.0018),mapPitch:(midi)=>applyScaleAttraction(midi,pitchSettings())});audio.setBpm(state.bpm);audio.setWaveform(state.waveform);audio.setBrightness(state.brightness);audio.setAmbience(state.ambience);
function pitchSettings(){return{mode:state.scale==='chromatic'?'chromatic':'scale',key:state.key,scale:state.scale==='chromatic'?'major':state.scale,attraction:state.attraction};}
function cloneStrokes(strokes){return strokes.map((s)=>({id:s.id,points:s.points.map((p)=>({...p}))}));}
function loadStrokes(){try{const data=JSON.parse(localStorage.getItem('museCanvas.strokes')||'[]');return Array.isArray(data)?data.filter((s)=>s&&Array.isArray(s.points)&&s.points.length>=2).slice(0,600):[];}catch{return[];}}
let saveTimer=null;function persistSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('museCanvas.strokes',JSON.stringify(state.strokes));}catch{}},120);}
function pushHistory(previous){state.past.push(cloneStrokes(previous));if(state.past.length>40)state.past.shift();state.future=[];syncHistoryButtons();}
function syncHistoryButtons(){controls.undo.disabled=!state.past.length;controls.redo.disabled=!state.future.length;}
function undo(){if(!state.past.length)return;state.future.push(cloneStrokes(state.strokes));state.strokes=state.past.pop();persistSoon();syncHistoryButtons();}
function redo(){if(!state.future.length)return;state.past.push(cloneStrokes(state.strokes));state.strokes=state.future.pop();persistSoon();syncHistoryButtons();}
function worldPointFromEvent(e){const r=canvas.getBoundingClientRect(),w=screenToWorld({x:e.clientX-r.left,y:e.clientY-r.top},state.viewport,{width:r.width,height:r.height});w.x=Math.max(0,Math.min(1,w.x));return w;}
function strokePointFromEvent(e){return{...worldPointFromEvent(e),pressure:normalizePressure(e.pressure,e.pointerType),t:performance.now()};}
function newId(){return globalThis.crypto?.randomUUID?.()||`s-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
async function beginDraw(e){state.drawPointerId=e.pointerId;canvas.setPointerCapture?.(e.pointerId);const p=strokePointFromEvent(e);state.draft={id:newId(),points:[p]};try{await audio.startLiveVoice(p.y,p.pressure);}catch(error){showToast(error.message||'Audio unavailable');}}
function continueDraw(e){if(!state.draft||e.pointerId!==state.drawPointerId)return;const events=e.getCoalescedEvents?.()||[e];for(const sample of events){const p=strokePointFromEvent(sample);appendPoint(state.draft,p,.0012);audio.updateLiveVoice(p.y,p.pressure);}}
function finishDraw(e){if(!state.draft||e.pointerId!==state.drawPointerId)return;audio.stopLiveVoice();if(state.draft.points.length>=2){pushHistory(state.strokes);state.strokes=[...state.strokes,state.draft];persistSoon();}state.draft=null;state.drawPointerId=null;}
function eraserMetric(){const r=canvas.getBoundingClientRect(),radius=25*state.viewport.xSpan/Math.max(1,r.width),yScale=(r.height*state.viewport.xSpan)/(Math.max(1,r.width)*state.viewport.ySpan);return{radius,scale:{xScale:1,yScale}};}
function eraseAt(e){const world=worldPointFromEvent(e),r=canvas.getBoundingClientRect();state.eraserScreen={x:e.clientX-r.left,y:e.clientY-r.top};const{radius,scale}=eraserMetric(),before=state.strokes.map((s)=>`${s.id}:${s.points.length}`).join('|');state.strokes=eraseStrokeSegments(state.strokes,world,radius,scale);const after=state.strokes.map((s)=>`${s.id}:${s.points.length}`).join('|');if(before!==after)state.eraseChanged=true;}
function beginErase(e){state.drawPointerId=e.pointerId;state.eraseBaseline=cloneStrokes(state.strokes);state.eraseChanged=false;canvas.setPointerCapture?.(e.pointerId);eraseAt(e);}function continueErase(e){if(e.pointerId!==state.drawPointerId)return;for(const sample of(e.getCoalescedEvents?.()||[e]))eraseAt(sample);}function finishErase(e){if(e.pointerId!==state.drawPointerId)return;if(state.eraseChanged&&state.eraseBaseline){pushHistory(state.eraseBaseline);persistSoon();}state.eraseBaseline=null;state.eraseChanged=false;state.drawPointerId=null;state.eraserScreen=null;}
function handleTouchDown(e){state.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture?.(e.pointerId);resetTouchGesture();}
function handleTouchMove(e){if(!state.touches.has(e.pointerId))return;state.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=canvas.getBoundingClientRect(),size={width:r.width,height:r.height},points=[...state.touches.values()];if(points.length===1&&state.touchGesture?.type==='pan'){const p=points[0];state.viewport=panViewport(state.viewport,p.x-state.touchGesture.x,p.y-state.touchGesture.y,size);state.touchGesture={type:'pan',x:p.x,y:p.y};return;}if(points.length>=2){const[a,b]=points,center={x:(a.x+b.x)/2-r.left,y:(a.y+b.y)/2-r.top},distance=Math.hypot(a.x-b.x,a.y-b.y);if(state.touchGesture?.type==='pinch'){state.viewport=panViewport(state.viewport,center.x-state.touchGesture.center.x,center.y-state.touchGesture.center.y,size);state.viewport=zoomViewport(state.viewport,distance/Math.max(1,state.touchGesture.distance),center,size);}state.touchGesture={type:'pinch',center,distance};}}
function handleTouchUp(e){state.touches.delete(e.pointerId);resetTouchGesture();}
function resetTouchGesture(){const r=canvas.getBoundingClientRect(),points=[...state.touches.values()];if(points.length===1)state.touchGesture={type:'pan',x:points[0].x,y:points[0].y};else if(points.length>=2){const[a,b]=points;state.touchGesture={type:'pinch',center:{x:(a.x+b.x)/2-r.left,y:(a.y+b.y)/2-r.top},distance:Math.hypot(a.x-b.x,a.y-b.y)};}else state.touchGesture=null;}
canvas.addEventListener('pointerdown',(e)=>{e.preventDefault();if(pointerRole(e.pointerType)==='navigate')return handleTouchDown(e);state.tool==='erase'?beginErase(e):beginDraw(e);});
canvas.addEventListener('pointermove',(e)=>{e.preventDefault();if(pointerRole(e.pointerType)==='navigate')return handleTouchMove(e);if(state.tool==='erase'){const r=canvas.getBoundingClientRect();state.eraserScreen={x:e.clientX-r.left,y:e.clientY-r.top};continueErase(e);}else continueDraw(e);});
canvas.addEventListener('pointerup',(e)=>{e.preventDefault();if(pointerRole(e.pointerType)==='navigate')return handleTouchUp(e);state.tool==='erase'?finishErase(e):finishDraw(e);});canvas.addEventListener('pointercancel',(e)=>{if(pointerRole(e.pointerType)==='navigate')handleTouchUp(e);else state.tool==='erase'?finishErase(e):finishDraw(e);});canvas.addEventListener('pointerleave',(e)=>{if(e.pointerType==='mouse'&&state.tool==='erase'&&e.pointerId!==state.drawPointerId)state.eraserScreen=null;});
controls.play.addEventListener('click',async()=>{if(state.playing){audio.pause();state.playing=false;}else{try{audio.setBpm(state.bpm);await audio.play();state.playing=true;}catch(error){showToast(error.message||'Audio unavailable');}}syncPlayButton();});
controls.bpm.addEventListener('change',()=>{state.bpm=clampBpm(controls.bpm.value);controls.bpm.value=String(state.bpm);audio.setBpm(state.bpm);});controls.bpm.addEventListener('blur',()=>controls.bpm.dispatchEvent(new Event('change')));controls.key.addEventListener('change',()=>{state.key=Number(controls.key.value);});controls.scale.addEventListener('change',()=>{state.scale=controls.scale.value;});controls.tool.addEventListener('click',()=>{state.tool=state.tool==='draw'?'erase':'draw';controls.tool.classList.toggle('active',state.tool==='erase');controls.tool.setAttribute('aria-pressed',String(state.tool==='erase'));controls.toolLabel.textContent=state.tool==='erase'?'Erase':'Draw';canvas.style.cursor=state.tool==='erase'?'none':'crosshair';});controls.clear.addEventListener('click',()=>{if(!state.strokes.length)return;pushHistory(state.strokes);state.strokes=[];persistSoon();});controls.undo.addEventListener('click',undo);controls.redo.addEventListener('click',redo);controls.settings.addEventListener('click',()=>toggleSettings(true));controls.closeSettings.addEventListener('click',()=>toggleSettings(false));controls.wave.addEventListener('change',()=>{state.waveform=controls.wave.value;audio.setWaveform(state.waveform);});controls.brightness.addEventListener('input',()=>{state.brightness=Number(controls.brightness.value);audio.setBrightness(state.brightness);});controls.ambience.addEventListener('input',()=>{state.ambience=Number(controls.ambience.value);audio.setAmbience(state.ambience);});controls.attraction.addEventListener('input',()=>{state.attraction=Number(controls.attraction.value);});
document.addEventListener('keydown',(e)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.code==='Space'&&!['INPUT','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();controls.play.click();}if(e.key.toLowerCase()==='e')controls.tool.click();});
function toggleSettings(open){controls.settingsPanel.classList.toggle('open',open);controls.settingsPanel.setAttribute('aria-hidden',String(!open));}function syncPlayButton(){controls.play.classList.toggle('playing',state.playing);controls.play.setAttribute('aria-label',state.playing?'Pause loop':'Play loop');}
let toastTimer=null;function showToast(message,ms=1800){controls.toast.textContent=message;controls.toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>controls.toast.classList.remove('visible'),ms);}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(dpr,0,0,dpr,0,0);}
function pitchColor(midi,alpha=1,lightBoost=0){const n=Math.max(0,Math.min(1,(midi-36)/60)),h=188+n*78,l=66+n*10+lightBoost;return`hsla(${h}, 76%, ${l}%, ${alpha})`;}
function drawStroke(stroke,r,isDraft=false){if(!stroke||stroke.points.length<2)return;ctx.lineCap='round';ctx.lineJoin='round';for(let pass=0;pass<2;pass+=1){for(let i=1;i<stroke.points.length;i+=1){const a=stroke.points[i-1],b=stroke.points[i],p1=worldToScreen(a,state.viewport,r),p2=worldToScreen(b,state.viewport,r);if((p1.x<-40&&p2.x<-40)||(p1.x>r.width+40&&p2.x>r.width+40))continue;const pressure=(a.pressure+b.pressure)/2;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);if(pass===0){ctx.strokeStyle=pitchColor((a.y+b.y)/2,isDraft?.20:.13);ctx.lineWidth=5+pressure*8;ctx.shadowBlur=16+pressure*10;ctx.shadowColor=pitchColor((a.y+b.y)/2,.42);}else{ctx.strokeStyle=pitchColor((a.y+b.y)/2,isDraft?.94:.72,isDraft?5:0);ctx.lineWidth=1.6+pressure*3.8;ctx.shadowBlur=isDraft?9:4;ctx.shadowColor=pitchColor((a.y+b.y)/2,.5);}ctx.stroke();}}ctx.shadowBlur=0;}
function renderFrame(){resizeCanvas();const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);drawAtmosphere(r);drawBarHints(r);for(const stroke of state.strokes)drawStroke(stroke,r,false);if(state.draft)drawStroke(state.draft,r,true);if(state.playing){const phase=audio.getPhase();drawPlayhead(phase,r);drawActiveHits(phase,r);}if(state.tool==='erase'&&state.eraserScreen)drawEraserCursor();requestAnimationFrame(renderFrame);}
function drawAtmosphere(r){const g=ctx.createRadialGradient(r.width*.52,r.height*.48,10,r.width*.52,r.height*.48,Math.max(r.width,r.height)*.72);g.addColorStop(0,'rgba(66, 75, 135, 0.025)');g.addColorStop(1,'rgba(0, 0, 0, 0)');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);}
function drawBarHints(r){ctx.save();for(let bar=0;bar<=4;bar+=1){const x=bar/4,s=worldToScreen({x,y:state.viewport.yCenter},state.viewport,r);if(s.x<-1||s.x>r.width+1)continue;ctx.beginPath();ctx.moveTo(s.x,0);ctx.lineTo(s.x,r.height);ctx.strokeStyle=bar===0||bar===4?'rgba(194, 207, 255, 0.055)':'rgba(194, 207, 255, 0.028)';ctx.lineWidth=1;ctx.stroke();}ctx.restore();}
function drawPlayhead(phase,r){const s=worldToScreen({x:phase,y:state.viewport.yCenter},state.viewport,r);if(s.x<-3||s.x>r.width+3)return;const g=ctx.createLinearGradient(0,0,0,r.height);g.addColorStop(0,'rgba(178, 200, 255, 0.06)');g.addColorStop(.2,'rgba(188, 211, 255, 0.54)');g.addColorStop(.8,'rgba(129, 236, 241, 0.42)');g.addColorStop(1,'rgba(129, 236, 241, 0.04)');ctx.save();ctx.beginPath();ctx.moveTo(s.x,0);ctx.lineTo(s.x,r.height);ctx.strokeStyle=g;ctx.lineWidth=1;ctx.shadowBlur=12;ctx.shadowColor='rgba(154, 208, 255, 0.34)';ctx.stroke();ctx.restore();}
function drawActiveHits(phase,r){const hits=sampleStrokeIntersections(state.strokes,phase,.0022).slice(0,12);for(const hit of hits){const s=worldToScreen({x:phase,y:hit.y},state.viewport,r);if(s.x<-20||s.x>r.width+20||s.y<-20||s.y>r.height+20)continue;const radius=8+(hit.pressure??.5)*9,g=ctx.createRadialGradient(s.x,s.y,0,s.x,s.y,radius);g.addColorStop(0,pitchColor(hit.y,.72,8));g.addColorStop(.25,pitchColor(hit.y,.21));g.addColorStop(1,pitchColor(hit.y,0));ctx.fillStyle=g;ctx.beginPath();ctx.arc(s.x,s.y,radius,0,Math.PI*2);ctx.fill();}}
function drawEraserCursor(){const{x,y}=state.eraserScreen;ctx.save();ctx.beginPath();ctx.arc(x,y,25,0,Math.PI*2);ctx.fillStyle='rgba(255, 207, 233, 0.025)';ctx.fill();ctx.strokeStyle='rgba(255, 207, 233, 0.38)';ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.stroke();ctx.restore();}
syncHistoryButtons();syncPlayButton();state.viewport=clampViewport(state.viewport);requestAnimationFrame(renderFrame);
if('serviceWorker'in navigator)window.addEventListener('load',()=>{navigator.serviceWorker.register(new URL('../sw.js',import.meta.url)).catch(()=>{});});
setTimeout(()=>{const seen=localStorage.getItem('museCanvas.hintSeen');if(!seen){showToast('Pencil to draw · Fingers to move & zoom',3500);try{localStorage.setItem('museCanvas.hintSeen','1');}catch{}}},500);
