import {getLoopDurationSeconds,getLoopPhase,midiToFrequency} from './music.js';
const AudioContextCtor=globalThis.AudioContext||globalThis.webkitAudioContext;
export class AudioEngine{
constructor({sampleAtX,mapPitch}){this.sampleAtX=sampleAtX;this.mapPitch=mapPitch;this.context=null;this.input=null;this.filter=null;this.compressor=null;this.wet=null;this.convolver=null;this.waveform='triangle';this.bpm=120;this.brightness=4200;this.ambience=.16;this.live=null;this.playing=false;this.startTime=0;this.pausedPhase=0;this.nextEventTime=0;this.schedulerId=null;this.lookAhead=.12;this.tickMs=25;}
async ensureContext(){if(!AudioContextCtor)throw new Error('Web Audio is not available in this browser.');if(!this.context)this.#createGraph();if(this.context.state==='suspended')await this.context.resume();return this.context;}
#createGraph(){const c=new AudioContextCtor({latencyHint:'interactive'}),input=c.createGain();input.gain.value=.9;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=this.brightness;filter.Q.value=.55;const dry=c.createGain();dry.gain.value=.96;const convolver=c.createConvolver();convolver.buffer=this.#makeImpulse(c,1.25,2.8);const wet=c.createGain();wet.gain.value=this.ambience;const comp=c.createDynamicsCompressor();comp.threshold.value=-16;comp.knee.value=12;comp.ratio.value=6;comp.attack.value=.004;comp.release.value=.16;input.connect(filter);filter.connect(dry);dry.connect(comp);filter.connect(convolver);convolver.connect(wet);wet.connect(comp);comp.connect(c.destination);this.context=c;this.input=input;this.filter=filter;this.convolver=convolver;this.wet=wet;this.compressor=comp;}
#makeImpulse(c,seconds,decay){const length=Math.floor(c.sampleRate*seconds),buffer=c.createBuffer(2,length,c.sampleRate);for(let channel=0;channel<2;channel+=1){const data=buffer.getChannelData(channel);let seed=1337+channel*97;for(let i=0;i<length;i+=1){seed=(seed*1664525+1013904223)>>>0;const noise=(seed/0xffffffff)*2-1;data[i]=noise*((1-i/length)**decay)*.42;}}return buffer;}
setWaveform(value){this.waveform=['sine','triangle','sawtooth','square'].includes(value)?value:'triangle';if(this.live?.oscillator)this.live.oscillator.type=this.waveform;}
setBrightness(value){this.brightness=Math.min(12000,Math.max(250,Number(value)||4200));if(this.filter&&this.context)this.filter.frequency.setTargetAtTime(this.brightness,this.context.currentTime,.03);}
setAmbience(value){this.ambience=Math.min(.6,Math.max(0,Number(value)||0));if(this.wet&&this.context)this.wet.gain.setTargetAtTime(this.ambience,this.context.currentTime,.04);}
setBpm(nextBpm){const next=Math.min(240,Math.max(40,Number(nextBpm)||120));if(this.context&&this.playing){const phase=this.getPhase();this.bpm=next;this.startTime=this.context.currentTime-phase*getLoopDurationSeconds(this.bpm);this.nextEventTime=this.context.currentTime+.02;}else this.bpm=next;}
async startLiveVoice(midi,velocity){const c=await this.ensureContext();this.stopLiveVoice();const osc=c.createOscillator(),gain=c.createGain();osc.type=this.waveform;osc.frequency.value=midiToFrequency(this.mapPitch(midi));gain.gain.setValueAtTime(.0001,c.currentTime);gain.gain.exponentialRampToValueAtTime(this.#liveGain(velocity),c.currentTime+.012);osc.connect(gain);gain.connect(this.input);osc.start();this.live={oscillator:osc,gain};}
updateLiveVoice(midi,velocity){if(!this.context||!this.live)return;const now=this.context.currentTime;this.live.oscillator.frequency.setTargetAtTime(midiToFrequency(this.mapPitch(midi)),now,.012);this.live.gain.gain.setTargetAtTime(this.#liveGain(velocity),now,.018);}
stopLiveVoice(){if(!this.context||!this.live)return;const{oscillator,gain}=this.live,now=this.context.currentTime;gain.gain.cancelScheduledValues(now);gain.gain.setTargetAtTime(.0001,now,.018);try{oscillator.stop(now+.09);}catch{}this.live=null;}
#liveGain(v){return Math.max(.008,Math.min(.15,.018+v*.11));}
async play(){const c=await this.ensureContext();if(this.playing)return;this.playing=true;const duration=getLoopDurationSeconds(this.bpm);this.startTime=c.currentTime+.035-this.pausedPhase*duration;this.nextEventTime=c.currentTime+.04;this.#startScheduler();}
pause(){if(!this.playing)return;this.pausedPhase=this.getPhase();this.playing=false;if(this.schedulerId)clearInterval(this.schedulerId);this.schedulerId=null;}
reset(){this.pause();this.pausedPhase=0;}
getPhase(){if(!this.context||!this.playing)return this.pausedPhase;return getLoopPhase(this.context.currentTime,this.startTime,this.bpm);}
#startScheduler(){if(this.schedulerId)clearInterval(this.schedulerId);const tick=()=>{if(!this.playing||!this.context)return;const horizon=this.context.currentTime+this.lookAhead;while(this.nextEventTime<horizon){const phase=getLoopPhase(this.nextEventTime,this.startTime,this.bpm);const hits=this.sampleAtX(phase).sort((a,b)=>(b.pressure??.5)-(a.pressure??.5)).slice(0,8);for(const hit of hits)this.#scheduleTone(hit.y,hit.pressure??.5,this.nextEventTime);this.nextEventTime+=this.#samplePeriod();}};tick();this.schedulerId=setInterval(tick,this.tickMs);}
#samplePeriod(){return Math.min(.04,Math.max(.014,getLoopDurationSeconds(this.bpm)/320));}
#scheduleTone(midi,velocity,when){if(!this.context||when<this.context.currentTime-.01)return;const osc=this.context.createOscillator(),gain=this.context.createGain();osc.type=this.waveform;osc.frequency.setValueAtTime(midiToFrequency(this.mapPitch(midi)),when);const peak=Math.max(.0025,Math.min(.034,.006+velocity*.026)),end=when+Math.max(.045,this.#samplePeriod()*2.4);gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(peak,when+.006);gain.gain.exponentialRampToValueAtTime(.0001,end);osc.connect(gain);gain.connect(this.input);osc.start(when);osc.stop(end+.01);}
async dispose(){this.reset();this.stopLiveVoice();if(this.context)await this.context.close();this.context=null;}}
